"""
ts_model.py — Amazon Chronos zero-shot price forecasting.

The Chronos pipeline is loaded LAZILY on the first predict_stock_prices() call.
torch and chronos are NOT imported at module level — they load only when a
forecast is actually requested, saving ~500MB RAM at startup.
"""


# Global pipeline reference — None until first forecast request
_pipeline = None


def _get_pipeline():
    """
    Lazy-load the Amazon Chronos T5 Tiny forecasting pipeline.
    torch and chronos are imported here, not at module level.
    """
    global _pipeline
    if _pipeline is None:
        import torch  # noqa: F401  (needed by chronos internals)
        from chronos import BaseChronosPipeline
        print("  [Forecasting] Loading Chronos T5 Tiny model on CPU...")
        # Force CPU: AMD GPUs are not supported by PyTorch CUDA.
        _pipeline = BaseChronosPipeline.from_pretrained(
            "amazon/chronos-t5-tiny",
            device_map="cpu",
        )
    return _pipeline


def predict_stock_prices(symbol: str, exchange: str = "NSE", horizon_days: int = 10) -> dict:
    """
    Forecast the next N closing prices for a stock using Amazon Chronos.

    Args:
        symbol       : NSE/BSE ticker without suffix.
        exchange     : 'NSE' or 'BSE'.
        horizon_days : Number of trading days to forecast (recommended 5–20).

    Returns:
        Dict with historical_dates, historical_closes, forecast_median,
        forecast_low, forecast_high, horizon_days, and a note.
        On error, returns {"error": str, "symbol": symbol}.
    """
    import torch
    from tools.stock_data import get_stock_history

    try:
        history = get_stock_history(symbol, exchange, period="3mo", interval="1d")
        if "error" in history:
            return history

        closes          = history["close"]
        historical_dates = history["dates"]

        context  = torch.tensor(closes, dtype=torch.float32)
        pipeline = _get_pipeline()

        quantiles, _ = pipeline.predict_quantiles(
            inputs=context,
            prediction_length=horizon_days,
            quantile_levels=[0.1, 0.5, 0.9],
        )

        # quantiles shape: [batch=1, horizon, levels=3]
        forecast_low    = [round(x, 2) for x in quantiles[0, :, 0].tolist()]
        forecast_median = [round(x, 2) for x in quantiles[0, :, 1].tolist()]
        forecast_high   = [round(x, 2) for x in quantiles[0, :, 2].tolist()]

        return {
            "symbol":            symbol,
            "chart_type":        "forecast",
            "historical_dates":  historical_dates,
            "historical_closes": closes,
            "forecast_median":   forecast_median,
            "forecast_low":      forecast_low,
            "forecast_high":     forecast_high,
            "horizon_days":      horizon_days,
            "note": (
                "This forecast is generated by a statistical model using price patterns only. "
                "It does not account for news, earnings, or macro events. "
                "This is for educational purposes and not financial advice."
            ),
        }

    except Exception as e:
        return {"error": str(e), "symbol": symbol}
